# Generated by Django 3.0.8 on 2020-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=10000)),
                ('number', models.IntegerField()),
                ('desc', models.TextField(max_length=10000)),
                ('whatsapp', models.TextField(max_length=255)),
                ('twitter', models.TextField(max_length=255)),
                ('instagram', models.TextField(max_length=255)),
                ('facebook', models.TextField(max_length=255)),
            ],
        ),
    ]
