# Generated by Django 3.0.8 on 2020-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='imageone',
            field=models.ImageField(default=0, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
