# Generated by Django 3.0.8 on 2020-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_accounts_imageone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='imageone',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
